# Generated by Django 5.2.1 on 2025-09-01 05:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portexpense',
            name='in_out',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=3),
        ),
        migrations.AlterField(
            model_name='portexpense',
            name='customs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='portexpense',
            name='gate_no',
            field=models.CharField(choices=[('north_gate', 'North Gate'), ('bandar_area', 'Bandar Area'), ('west_gate_1', 'West Gate 1'), ('west_gate_2', 'West Gate 2'), ('west_gate_3', 'West Gate 3'), ('cj_13', 'CJ 13')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portexpense',
            name='kpt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='portexpense',
            name='road_tax_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
