# Generated by Django 5.2.1 on 2025-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_portexpense_in_out_alter_portexpense_customs_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalvoucher',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
