# Generated by Django 4.2.21 on 2025-05-25 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_contractors_from_existing_data(apps, schema_editor):
    """
    Create ContractorMaster records from existing LabourCost contractor_name values
    """
    LabourCost = apps.get_model('operations', 'LabourCost')
    ContractorMaster = apps.get_model('operations', 'ContractorMaster')
    User = apps.get_model('authentication', 'User')
    
    # Get the first admin user to assign as creator
    admin_user = User.objects.filter(role='admin').first()
    if not admin_user:
        admin_user = User.objects.first()
    
    if admin_user:
        # Get unique contractor names from existing labour costs
        contractor_names = LabourCost.objects.values_list('contractor_name', flat=True).distinct()
        
        for name in contractor_names:
            if name and name.strip():  # Only create if name is not empty
                ContractorMaster.objects.get_or_create(
                    name=name.strip(),
                    defaults={
                        'created_by': admin_user,
                        'is_active': True
                    }
                )


def reverse_create_contractors(apps, schema_editor):
    """
    Reverse migration - delete all ContractorMaster records
    """
    ContractorMaster = apps.get_model('operations', 'ContractorMaster')
    ContractorMaster.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_add_invoice_tracking_to_labour_cost'),
    ]

    operations = [
        # Create ContractorMaster model
        migrations.CreateModel(
            name='ContractorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Migrate existing contractor names to ContractorMaster
        migrations.RunPython(create_contractors_from_existing_data, reverse_create_contractors),
    ]
