# Generated by Django 4.2.21 on 2025-05-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_update_labour_cost_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractormaster',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contractormaster',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='contractormaster',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contractormaster',
            name='phone_number',
        ),
    ]
