# Generated by Django 4.2.21 on 2025-05-25 20:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_simplify_contractor_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourcost',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ratemaster',
            options={'ordering': ['contractor__name', 'labour_type']},
        ),
        migrations.RemoveField(
            model_name='labourcost',
            name='amount',
        ),
        migrations.AddField(
            model_name='labourcost',
            name='shift',
            field=models.CharField(blank=True, choices=[('1st_shift', '1st Shift'), ('2nd_shift', '2nd Shift'), ('3rd_shift', '3rd Shift')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratemaster',
            name='contractor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='operations.contractormaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratemaster',
            name='labour_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('tonnes', 'Tonnes'), ('fixed', 'Fixed')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='invoice_received',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='labour_count_tonnage',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='labour_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('tonnes', 'Tonnes'), ('fixed', 'Fixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.cargooperation'),
        ),
        migrations.AlterField(
            model_name='labourcost',
            name='work_type',
            field=models.CharField(choices=[('loading', 'Loading'), ('unloading', 'Unloading'), ('shifting', 'Shifting'), ('sorting', 'Sorting'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='ratemaster',
            unique_together={('contractor', 'labour_type')},
        ),
        migrations.RemoveField(
            model_name='ratemaster',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ratemaster',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='ratemaster',
            name='party',
        ),
        migrations.RemoveField(
            model_name='ratemaster',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='ratemaster',
            name='unit',
        ),
    ]
