# Generated by Django 4.2.21 on 2025-05-26 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_update_labour_cost_and_rate_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcost',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
