# Generated by Django 4.2.21 on 2025-06-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_equipment_billing_quantity_equipment_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='billing_quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='invoice_received',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tonnage',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='total_amount',
        ),
        migrations.DeleteModel(
            name='EquipmentRateMaster',
        ),
    ]
