# Generated by Django 5.2.1 on 2025-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_equipment_billing_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Calculated quantity based on contract type', max_digits=10, null=True),
        ),
    ]
