# Generated by Django 5.2.1 on 2025-07-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_add_equipment_rate_master_and_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneouscost',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
