# Generated by Django 5.2.1 on 2025-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_add_bill_no_to_miscellaneous_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuestream',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
