# Generated by Django 5.2.1 on 2025-07-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_populate_service_and_unit_type_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuestream',
            name='service_type_temp',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='operations.servicetypemaster'),
        ),
        migrations.AddField(
            model_name='revenuestream',
            name='unit_type_temp',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='operations.unittypemaster'),
        ),
    ]
