# Generated by Django 5.2.1 on 2025-07-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_populate_temporary_fields'),
    ]

    operations = [
        # Remove old CharField fields
        migrations.RemoveField(
            model_name='revenuestream',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='revenuestream',
            name='unit_type',
        ),
        # Rename temporary fields to final names
        migrations.RenameField(
            model_name='revenuestream',
            old_name='service_type_temp',
            new_name='service_type',
        ),
        migrations.RenameField(
            model_name='revenuestream',
            old_name='unit_type_temp',
            new_name='unit_type',
        ),
        # Make the fields required (remove null=True, blank=True)
        migrations.AlterField(
            model_name='revenuestream',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.servicetypemaster'),
        ),
        migrations.AlterField(
            model_name='revenuestream',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.unittypemaster'),
        ),
    ]
