# Generated by Django 5.2.1 on 2025-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_finalize_revenue_stream_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargooperation',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='cargooperation',
            name='project_status',
        ),
        migrations.AlterField(
            model_name='cargooperation',
            name='cargo_type',
            field=models.CharField(choices=[('paper_bales', 'Paper Bales'), ('raw_salt', 'Raw Salt'), ('coal', 'Coal'), ('silica', 'Silica'), ('breakbulk', 'Breakbulk'), ('container', 'Container'), ('bulk', 'Bulk'), ('project', 'Project Cargo'), ('others', 'Others')], max_length=50),
        ),
    ]
