# Generated by Django 5.2.1 on 2025-09-03 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_update_cargo_operation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentratemaster',
            options={'ordering': ['party__name', 'vehicle_type__name', 'work_type__name', 'contract_type', '-effective_from']},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentratemaster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipmentratemaster',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipmentratemaster',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or conditions'),
        ),
        migrations.AddField(
            model_name='equipmentratemaster',
            name='unit',
            field=models.CharField(choices=[('per_hour', 'Per Hour'), ('per_shift', 'Per Shift'), ('per_tonne', 'Per Tonne'), ('fixed_rate', 'Fixed Rate'), ('per_day', 'Per Day'), ('per_trip', 'Per Trip')], default='per_hour', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentratemaster',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Leave blank for indefinite validity', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentratemaster',
            unique_together={('party', 'vehicle_type', 'work_type', 'contract_type', 'effective_from')},
        ),
    ]
