# Generated by Django 5.2.1 on 2025-09-04 10:38

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_alter_equipmentratemaster_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('ownership', models.CharField(choices=[('owned', 'Company Owned'), ('hired', 'Hired/Contract')], default='hired', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('owner_name', models.CharField(blank=True, help_text='Owner name for hired vehicles', max_length=100, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('capacity', models.CharField(blank=True, help_text='Vehicle capacity (e.g., 10 MT, 25 CBM)', max_length=50, null=True)),
                ('make_model', models.CharField(blank=True, help_text='Vehicle make and model', max_length=100, null=True)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vehicletype')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance'), ('puc', 'PUC (Pollution Under Control)'), ('rc', 'RC (Registration Certificate)'), ('fitness', 'Fitness Certificate'), ('road_tax', 'Road Tax'), ('permit', 'Permit'), ('fastag', 'FASTag'), ('commercial_permit', 'Commercial Permit'), ('goods_permit', 'Goods Permit'), ('other', 'Other')], max_length=30)),
                ('document_number', models.CharField(help_text='Policy No., RC No., Certificate No., etc.', max_length=100)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=operations.models.vehicle_document_upload_path)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('renewal_reference', models.ForeignKey(blank=True, help_text='Reference to the document this replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='operations.vehicledocument')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.vehicle')),
            ],
            options={
                'ordering': ['-added_on'],
                'indexes': [models.Index(fields=['vehicle', 'document_type', 'status'], name='operations__vehicle_a93558_idx'), models.Index(fields=['expiry_date'], name='operations__expiry__f87d6b_idx'), models.Index(fields=['status'], name='operations__status_181e03_idx')],
            },
        ),
    ]
