# Generated by Django 4.2.21 on 2025-09-08 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0023_purchaseorder_poitem_stock_issueslip_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderPurchaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_links', to='operations.purchaseorder')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_links', to='operations.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('work_order', 'purchase_order')},
            },
        ),
    ]
