# Generated by Django 4.2.21 on 2025-09-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_workorderpurchaselink'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workorderpurchaselink',
            constraint=models.UniqueConstraint(fields=('purchase_order',), name='unique_link_per_purchase_order'),
        ),
    ]
