# Generated by Django 4.2.21 on 2025-09-08 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0025_workorderpurchaselink_unique_link_per_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.IntegerField()),
                ('related_entity_type', models.CharField(max_length=32)),
                ('related_entity_id', models.IntegerField()),
                ('action', models.CharField(choices=[('link', 'Link'), ('unlink', 'Unlink')], max_length=16)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='operations__entity__668972_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='operations__related_e300c8_idx'), models.Index(fields=['action'], name='operations__action_638144_idx')],
            },
        ),
    ]
