# Generated by Django 5.2.1 on 2025-09-27 11:03

from django.db import migrations


def copy_vendor_data(apps, schema_editor):
    """
    Copy existing vendors to both POVendor and WOVendor tables
    """
    Vendor = apps.get_model('operations', 'Vendor')
    POVendor = apps.get_model('operations', 'POVendor')
    WOVendor = apps.get_model('operations', 'WOVendor')
    
    # Get all existing vendors
    vendors = Vendor.objects.all()
    
    for vendor in vendors:
        # Create POVendor
        po_vendor = POVendor.objects.create(
            name=vendor.name,
            contact_person=vendor.contact_person,
            phone_number=vendor.phone_number,
            email=vendor.email,
            address=vendor.address,
            is_active=vendor.is_active,
            created_by=vendor.created_by,
            created_at=vendor.created_at,
        )
        
        # Create WOVendor
        wo_vendor = WOVendor.objects.create(
            name=vendor.name,
            contact_person=vendor.contact_person,
            phone_number=vendor.phone_number,
            email=vendor.email,
            address=vendor.address,
            is_active=vendor.is_active,
            created_by=vendor.created_by,
            created_at=vendor.created_at,
        )


def reverse_copy_vendor_data(apps, schema_editor):
    """
    Reverse migration - clear the new vendor tables
    """
    POVendor = apps.get_model('operations', 'POVendor')
    WOVendor = apps.get_model('operations', 'WOVendor')
    
    POVendor.objects.all().delete()
    WOVendor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_add_vendor_models_only'),
    ]

    operations = [
        migrations.RunPython(copy_vendor_data, reverse_copy_vendor_data),
    ]
