# Generated by Django 5.2.1 on 2025-09-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_copy_vendor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='operations.povendor'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='operations.wovendor'),
        ),
    ]
