# Generated by Django 5.2.1 on 2025-09-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_migrate_vendor_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('PO', 'PO Vendor'), ('WO', 'WO Vendor')], max_length=10)),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Audit Log',
                'verbose_name_plural': 'Vendor Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor_type', 'vendor_id'], name='operations__vendor__463743_idx'), models.Index(fields=['action'], name='operations__action_08b9bd_idx'), models.Index(fields=['performed_by'], name='operations__perform_cc62e6_idx'), models.Index(fields=['created_at'], name='operations__created_ba8bcc_idx')],
            },
        ),
    ]
