# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def migrate_vehicle_types_to_master_data(apps, schema_editor):
    """
    Migrate existing VehicleType records to the master data list system
    """
    VehicleType = apps.get_model('operations', 'VehicleType')
    ListTypeMaster = apps.get_model('operations', 'ListTypeMaster')
    ListItemMaster = apps.get_model('operations', 'ListItemMaster')
    User = apps.get_model('authentication', 'User')
    
    # Get or create the equipment_vehicle_types list type
    equipment_list_type, created = ListTypeMaster.objects.get_or_create(
        code='equipment_vehicle_types',
        defaults={
            'name': 'Equipment Vehicle Types',
            'description': 'Vehicle types for equipment and vehicles management',
            'is_active': True,
        }
    )
    
    # Migrate existing VehicleType records to ListItemMaster
    existing_vehicle_types = VehicleType.objects.all()
    sort_order = 1
    
    for vehicle_type in existing_vehicle_types:
        # Create corresponding list item
        list_item, created = ListItemMaster.objects.get_or_create(
            list_type=equipment_list_type,
            name=vehicle_type.name,
            defaults={
                'code': vehicle_type.name.lower().replace(' ', '_').replace('/', '_'),
                'sort_order': sort_order,
                'is_active': vehicle_type.is_active,
                'created_by': vehicle_type.created_by,
                'created_at': vehicle_type.created_at,
            }
        )
        sort_order += 1
        
        # Store the mapping for later use
        vehicle_type.migrated_list_item_id = list_item.id
        vehicle_type.save()


def reverse_migrate_vehicle_types(apps, schema_editor):
    """
    Reverse migration - not implemented as it would be complex
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0034_add_additional_list_data'),
    ]

    operations = [
        # First, add a temporary field to store the mapping
        migrations.AddField(
            model_name='vehicletype',
            name='migrated_list_item_id',
            field=models.IntegerField(null=True, blank=True, help_text='Temporary field for migration'),
        ),
        
        # Run the migration function
        migrations.RunPython(
            migrate_vehicle_types_to_master_data,
            reverse_migrate_vehicle_types,
        ),
        
        # Add the new field that will reference ListItemMaster
        migrations.AddField(
            model_name='vehicletype',
            name='list_item',
            field=models.OneToOneField(
                'operations.ListItemMaster',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                help_text='Reference to master data list item'
            ),
        ),
    ] 