# Generated by Django 5.2.1 on 2025-09-28 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_add_additional_list_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type_code', models.CharField(max_length=50)),
                ('list_type_name', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List Item Audit Log',
                'verbose_name_plural': 'List Item Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['list_type_code', 'item_id'], name='operations__list_ty_10e3b7_idx'), models.Index(fields=['action'], name='operations__action_792174_idx'), models.Index(fields=['performed_by'], name='operations__perform_3c8035_idx'), models.Index(fields=['created_at'], name='operations__created_9da165_idx')],
            },
        ),
    ]
