# Generated by Django 5.2.1 on 2025-09-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_add_list_item_audit_log'),
        ('operations', '0036_complete_vehicle_type_migration'),
    ]

    operations = [
    ]
